### ISSUE TITLE
Add notification mail service as cronjob

### ISSUE THREAD

**Issue by hugotiburtino** [serlo/infrastructure-modules-api#17]
The new [notification mail service](https://github.com/serlo/notification-mail-service) has to be integrated as a cronjob.
It should run every hour and it should be in the `api` namespace.

Examples of other cronjobs:
- [cache worker](https://github.com/serlo/infrastructure-modules-api/tree/main/cache-worker)
- [legacy notification](https://github.com/serlo/infrastructure-modules-serlo.org/blob/5621c49/server/main.tf#L254)

Waiting for:
- [x] https://github.com/serlo/notification-mail-service/issues/1
- [x] https://github.com/serlo/notification-mail-service/issues/4

**Comment by MoeHome** [comment]
Completed
